server:
  port: 9081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ams?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Chen160121
logging:
  level:
    cn.tedu.csmall: trace

# custom configuration
csmall:
  jwt:
    secret-key : sd>/fd{}s1:2S_S+DF213sad12sas12ca2,2
    duration-in-minute : 14400


