server:
  port: 9081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ams?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Chen160121
logging:
  level:
    cn.tedu.csmall: trace


